In [4]:
import numpy as np
import matplotlib.pyplot as plt



In [9]:
v=np.array([1,2])
sum=np.sum(v)
print("The sum of v's elements is:", sum)

The sum of v's elements is: 3


In [7]:
A=np.array([[2,3],[6,5]])
At=np.transpose(A)
print("The transpose of A is:")
print(At)
av=A.dot(v)
print("The result of A.dot(v) is:")
print(av)

The transpose of A is:
[[2 6]
 [3 5]]
The result of A.dot(v) is:
[ 8 16]


In [11]:
eigenvalues, eigenvectors = np.linalg.eig(A)
print("The eigenvalues of A are:")
print(eigenvalues)
print("The eigenvectors of A are:")
print(eigenvectors)
eigen1 = eigenvalues[0]
eigen2 = eigenvalues[1]
eigenvec1 = eigenvectors[:,0]
eigenvec2 = eigenvectors[:,1]

The eigenvalues of A are:
[-1.  8.]
The eigenvectors of A are:
[[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


In [12]:
B=A*A
print("The matrix B=A*A is:")
print(B)
C=A**2
print("The matrix C=A**2 is:")
print(C)


The matrix B=A*A is:
[[ 4  9]
 [36 25]]
The matrix C=A**2 is:
[[ 4  9]
 [36 25]]


In [13]:
x=np.linspace(0,1,50)
I=np.sin(np.pi*x)**2
#using trapezoidal rule
def trapezoidal(x,f):
    n=len(x)
    h=x[1]-x[0]
    integral=(f[0]+f[n-1])/2
    for i in range(1,n-1):
        integral+=f[i]
    integral=integral*h
    return integral
integral_trap=trapezoidal(x,I)
print("The integral using trapezoidal rule is:", integral_trap)


The integral using trapezoidal rule is: 0.5
